baseURL = "http://tiagogoncalv.es/"
languageCode = "en-us"
title = "Tiago Gonçalves Personal Website"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Tiago Gonçalves Personal Website"
  keywords = "homepage, design, portfolio, ui, ux"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:me@tiagogoncalv.es"

  [[params.social]]
    name = "linkedin"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "twitter"
    url  = "https://github.com/"

  [[params.social]]
    name = "instagram"
    url  = "https://www.linkedin.com/"
    
[languages]
  [languages.en]
    title = "Hi, I'm Tiago Gonçalves 👋"
    homesubtitle = "I'm a UX/UI Designer based in Porto, Portugal"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "tiago"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

customCSS = ["css/styles.css"]

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"